[package]
name = "ore-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = { version = "0.29.0", features = ["async"] }
anchor-spl =  { version = "0.29.0", features = ["token"] }
base64 = "0.21.5"
cached = "0.46.1"
clap = { version = "4.4.12", features = ["derive"] }
futures = "0.3.30"
log = "0.4"
ore = { version = "0.1.0", path = "/home/ubuntu/ore/programs/ore" }
sha256 = "1.1.3"
solana-client = "1.16"
solana-sdk = "1.16"
tokio = "1.35.1"
bincode = "1.3.3"
