[package]
name = "ore-cli"
version = "0.1.1"
description = "A command line interface for the Ore program."
license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "ore"
path = "src/main.rs"

[features]
default = []
admin = []

[dependencies]
bs64 = "0.1.2"
cached = "0.46.1"
clap = { version = "4.4.12", features = ["derive"] }
futures = "0.3.30"
log = "0.4"
ore = { package = "ore-program", version = "0.0.6" }
solana-client = "^1.16"
solana-program = "^1.16"
solana-sdk = "^1.16"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ] }
tokio = "1.35.1"
bincode = "1.3.3"
solana-cli-config = "1.18.5"
crossterm = "0.27.0"
